### ISSUE TITLE
支持聚合统计？

### ISSUE THREAD

**Issue by guzishiwo** [xinz/ex_aliyun_ots#42]
<img width="1373" alt="image" src="https://github.com/xinz/ex_aliyun_ots/assets/3472623/b105d601-0041-413e-ae6b-5a170a5b3ab2">

https://help.aliyun.com/zh/tablestore/developer-reference/aggregation-4?spm=a2c4g.11186623.0.0.15641973vnWABe

**Comment by xinz** [comment]
hello @guzishiwo ，预期这些多元索引的聚合统计功能都已经实现了，请查看这里的[文档说明](https://hexdocs.pm/ex_aliyun_ots/ExAliyunOts.Search.html#agg_avg/3)，另，[测试用例](https://github.com/xinz/ex_aliyun_ots/blob/master/test/mixin/search_test.exs)也有一些参考使用，希望对你有帮助。
